### ISSUE TITLE
Grammar missing required scopeName Error

### ISSUE THREAD

**Issue by janakg** [marko-js/website#31]
I am getting the below error, please let me know if I am missing some thing.

markojs-website/node_modules/routes-table/index.js:112
          throw e;
          ^
Error: Unable to compile template at path "markojs-website/routes/index/components/home-components/index.marko". Error: Grammar missing required scopeName property: markojs-website/node_modules/language-javascript/grammars/tree-sitter-javascript.cson
  at transformNode (markojs-website/node_modules/marko/src/compiler/Compiler.js:31:27)
  at transformTreeHelper (markojs-website/node_modules/marko/src/compiler/Compiler.js:36:5)
  at markojs-website/node_modules/marko/src/compiler/Compiler.js:47:9
  at ArrayContainer.forEach (markojs-website/node_modules/marko/src/compiler/ast/ArrayContainer.js:18:26)
  at HtmlElement.forEachChild (markojs-website/node_modules/marko/src/compiler/ast/Node.js:142:23)
  at transformTreeHelper (markojs-website/node_modules/marko/src/compiler/Compiler.js:46:10)
  at markojs-website/node_modules/marko/src/compiler/Compiler.js:47:9
  at ArrayContainer.forEach (markojs-website/node_modules/marko/src/compiler/ast/ArrayContainer.js:18:26)
  at HtmlElement.forEachChild (markojs-website/node_modules/marko/src/compiler/ast/Node.js:142:23)
  at transformTreeHelper (markojs-website/node_modules/marko/src/compiler/Compiler.js:46:10)
  at markojs-website/node_modules/marko/src/compiler/Compiler.js:47:9
  at ArrayContainer.forEach (markojs-website/node_modules/marko/src/compiler/ast/ArrayContainer.js:18:26)
  at TemplateRoot.forEachChild (markojs-website/node_modules/marko/src/compiler/ast/Node.js:142:23)
  at transformTreeHelper (markojs-website/node_modules/marko/src/compiler/Compiler.js:46:10)
  at transformTree (markojs-website/node_modules/marko/src/compiler/Compiler.js:66:9)
  at Compiler.compile (markojs-website/node_modules/marko/src/compiler/Compiler.js:161:30)
  at _compile (markojs-website/node_modules/marko/src/compiler/index.js:99:33)
  at Object.compile (markojs-website/node_modules/marko/src/compiler/index.js:113:12)
  at doLoad (markojs-website/node_modules/marko/src/loader/index-default.js:156:45)
  at load (markojs-website/node_modules/marko/src/loader/index-default.js:35:16)
  at Object.<anonymous> (markojs-website/routes/index/index.marko.js:16:32)
  at Module._compile (module.js:570:32)
  at Object.markoRequireExtension [as .marko] (markojs-website/node_modules/marko/src/node-require/index.js:124:16)
  at Module.load (module.js:487:32)
  at tryModuleLoad (module.js:446:12)
  at Function.Module._load (module.js:438:3)
  at Module.require (module.js:497:17)
  at require (internal/module.js:20:19)
  at tryRequire (markojs-website/node_modules/try-require/index.js:18:16)
  at Object.onRoute (markojs-website/node_modules/marko-starter/src/util/loadFilesystemRoutes.js:27:20)
  at buildRoute (markojs-website/node_modules/routes-table/index.js:160:37)
  at fs.stat.e (markojs-website/node_modules/routes-table/index.js:106:19)
  at FSReqWrap.oncomplete (fs.js:123:15)

**Comment by DylanPiercey** [comment]
The website has transitioned to `@marko/serve` and `@marko/build` and a much simpler setup. This issue should be resolved now!
